# Generated by Django 4.2.7 on 2025-01-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safezone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('medical', 'Medical Supplies'), ('rescue', 'Rescue Teams'), ('food', 'Food Supplies'), ('shelter', 'Shelter')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(default='available', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safezone.safezone')),
            ],
        ),
    ]
